---
# name: Install preq. packages
#  ansible.builtin.apt:
#    name: "{{ item }}"
#    state: present
#  loop:
#    - curl

#- name: Download Gitlab Runner deb package
#  ansible.builtin.shell:
#    cmd: "curl -LJO https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"

#- name: Install Gitlab runner package
#  ansible.builtin.shell:
#    cmd: "dpkg -i gitlab-runner_amd64.deb"

- name: Download repo script
  ansible.builtin.get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: "/root/script.deb.sh"
    mode: 0700

- name: Run repo install script
  ansible.builtin.shell:
    cmd: "/root/script.deb.sh"

- name: APT install gitlab-runner
  ansible.builtin.apt:
    name: gitlab-runner
    state: latest
    update_cache: yes

- name: Start gitlab-runner
  ansible.builtin.service:
    name: gitlab-runner
    enabled: yes
    state: started

- name: Write deploy-www script
  ansible.builtin.template:
    src: "deploy-www.j2"
    dest: "/usr/local/sbin/deploy-www"
    mode: 700

- name: Add sudo rule for chown
  community.general.sudoers:
    name: allow-deploy-www
    state: present
    user: gitlab-runner
    commands: /usr/local/sbin/deploy-www

